### ISSUE TITLE
Example Heroku app not found

### ISSUE THREAD

**Issue by ghost** [mhjort/clj-gatling-example#1]
curl -I  http://clj-gatling-demo-server.herokuapp.com/

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 0
Server: http-kit
Date: Tue, 31 May 2016 14:56:26 GMT
Via: 1.1 vegur

**Comment by mhjort** [comment]
It is a hobby Heroku app that is stopped when it's not used. It should
start the app when you do few requests

**Comment by mhjort** [comment]
There is also clj-gatling-demo-server repository. If you want you can check
that out and run locally
